---
- import_tasks: preflight.yml

- import_tasks: build.yml

### Only use one method to expose metrics, exporter.yml or cron.yml

### Comment in if going to use the exporter to expose metrics
- import_tasks: exporter.yml

### Comment in if going to use the node_exporter text collecter to collect metrics
# - import_tasks: cron.yml