---
- name: Install dependencies
  package:
    name: "{{ item }}"
    state: present
  register: _install_dep_packages
  until: _install_dep_packages is success
  retries: 5
  delay: 2
  with_items: "{{ zpool_prometheus_dependencies }}"

- name: Create the zpool_prometheus group
  group:
    name: "{{ zpool_prometheus_group }}"
    state: present
    system: true
  when: zpool_prometheus_group != "root"

- name: Create the zpool_prometheus user
  user:
    name: "{{ zpool_prometheus_user }}"
    groups: "{{ zpool_prometheus_group }}"
    append: true
    shell: /usr/sbin/nologin
    system: true
    createhome: false
    home: /
  when: zpool_prometheus_user != "root"

- name: Create zpool_prometheus directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ zpool_prometheus_user }}"
    group: "{{ zpool_prometheus_group }}"
    mode: 0755
  with_items:
    - "{{ zpool_prometheus_root_dir }}"
    - "{{ zpool_prometheus_config_dir }}"
